ID_GENDER_UNKNOWN = 0
ID_GENDER_FEMALE = 1
ID_GENDER_MALE = 2
MAP_GENDER_ID = {
    "unknown": ID_GENDER_UNKNOWN,
    "female": ID_GENDER_FEMALE,
    "male": ID_GENDER_MALE,
}

# ARG NAMES
ARG_PATH_CONTAINER_DATA = "PATH_CONTAINER_DATA"
ARG_PATH_CONTAINER_OUTPUT = "PATH_CONTAINER_OUTPUT"
ARG_SEED = "SEED"
ARG_NOMQUAM_THRESHOLD = "GI_NOMQUAM_THRESHOLD"
ARG_CSV_INT_FOLDER_METADATA = "CSV_INT_FOLDER_METADATA"
ARG_CSV_INT_FILE_DISAMB = "CSV_INT_FILE_DISAMB"
ARG_CSV_INT_FILE_LOG = "CSV_INT_FILE_LOG"
ARG_CSV_INT_N_PUBLICATIONS = "CSV_INT_N_PUBLICATIONS"
ARG_CSV_INT_FILE_CITATIONS = "CSV_INT_FILE_CITATIONS"

# Postgres
ARG_POSTGRES_HOST = "POSTGRES_HOST"
ARG_POSTGRES_USER = "POSTGRES_USER"
ARG_POSTGRES_PASSWORD = "POSTGRES_PASSWORD"
ARG_POSTGRES_PORT = "POSTGRES_PORT"
ARG_POSTGRES_DB = "POSTGRES_DB"
ARG_POSTGRES_DB_APS = "POSTGRES_DB_APS"