ID_GENDER_UNKNOWN = 0
ID_GENDER_FEMALE = 1
ID_GENDER_MALE = 2
MAP_GENDER_ID = {
    "unknown": ID_GENDER_UNKNOWN,
    "female": ID_GENDER_FEMALE,
    "male": ID_GENDER_MALE,
}

# ARG NAMES
ARG_FOLDER_DATA = "FOLDER_DATA"
ARG_FOLDER_OUTPUT = "FOLDER_OUTPUT"
ARG_SEED = "SEED"
ARG_NOMQUAM_THRESHOLD = "GI_NOMQUAM_THRESHOLD"
ARG_CSV_INT_FOLDER_METADATA = "CSV_INT_FOLDER_METADATA"
ARG_CSV_INT_FILE_DISAMB = "CSV_INT_FILE_DISAMB"
ARG_CSV_INT_FILE_LOG = "CSV_INT_FILE_LOG"
ARG_CSV_INT_N_PUBLICATIONS = "CSV_INT_N_PUBLICATIONS"
ARG_CSV_INT_FILE_CITATIONS = "CSV_INT_FILE_CITATIONS"